### ISSUE TITLE
Weird type conversion when formatting table 

### ISSUE THREAD

**Issue by ZeroRin** [masaccio/compact-json#10]
running the following code
```python
from compact_json import Formatter

data = [{'a': '0', 'b': '1', 'c':'0'}, {'a': '0', 'b': 1}]

formatter = Formatter(always_expand_depth=0)
print(formatter.serialize(data))
formatter.table_dict_minimum_similarity=100
print(formatter.serialize(data))
```
results in the following output
```console
$ python test.py
C:\Users\ZeroRin\Documents\Projects\compact-json\src\compact_json\formatter.py:68: RuntimeWarning: handled quantize error (please report an issue)
  warnings.warn(
[
    { "a": "0", "b": 0, "c": "0" },
    { "a": "0", "b": 1           }
]
[
    {"a": "0", "b": "1", "c": "0"},
    {"a": "0", "b": 1}
]
```
A warning is raised during the first formatting and the output somehow changed the value of `data[0]['b']` from string `"1"` to number `0`. During the second run where the output is not formatted as table, the output is correct

**Comment by masaccio** [comment]
The other solution (which doesn't fix the underlying passing of an invalid string to `_fixed_value` is to change the return value in the exception to `return value`. I've merged your code but also added the fallback in the exception so that the value isn't squashed even in the earning case,
