### ISSUE TITLE
The length computation of the last line in a multi-line is wrong

### ISSUE THREAD

**Issue by ZeroRin** [masaccio/compact-json#2]
https://github.com/masaccio/compact-json/blob/234356f5eb7aa335e1193c49cbad72589d8145a5/src/compact_json/formatter.py#L431
the current code results in a "tail" at the last line as the length of the last element is set to 0:
![image](https://user-images.githubusercontent.com/14952735/186339973-ad259078-0b58-48e2-980b-18c96fe71fb3.png)

I think this line should be changed to
```python
item_length + len(self.padded_comma_str)
```
which take into account the comma length no matter whether there will be a comma after the item. This could prevent such tail from happening when the max length is exactly 1 character less than the length of k elements with trailing comma. For example (I edited the bugged line to `item_length + (len(self.padded_comma_str) if not_last_item else 0)` before running the following code):
![image](https://user-images.githubusercontent.com/14952735/186341586-8b3ba941-baf8-4bcb-9336-cade47f4c28a.png)

**Comment by masaccio** [comment]
Many thanks for the patch. Latest PyPI has the change.
