### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by jsh9** [masaccio/compact-json#24]
Hi authors, thank you for writing this awesome tool!  

JSON readability is very important but I think it's overlooked by the standard library.

May I request the following features to make this library easier to use?

1. Could you add a `dump` method to directly dump the re-formatted JSON string to a JSON file?
2. Would it be possible to add a sanity checking method to check that the deserialized objects from the old string and the new string are identical?
3. Could you add a command line argument --output-file and let users directly create a new JSON file with formatted contents?
4. Could you register a command line entry point, so that users can use this tool in the command line with `compact-json ...` instead of `_compact_json.py ...`?

--------------------
Additional notes for Request No. 4 above:

I see that this package uses `poetry`.  I'm not so familiar with `poetry` so I asked ChatGPT how to register an entry point with `poetry`.  Below is my Q&A with ChatGPT:

#### Question:

How do I register a command line entry point for a Python package when I'm using poetry?

#### Answer:

To register a command line entry point for a Python package when using Poetry, you can use the `console_scripts` section in your `pyproject.toml` file.

Here's an example `pyproject.toml` file:

```
[tool.poetry]
name = "mypackage"
version = "0.1.0"
description = "My Python package"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.scripts]
mypackage-cli = "mypackage.cli:main"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
```

In this example, we have specified a script called `mypackage-cli` which points to a function called `main` in a module called `cli` inside a package called `mypackage`.

To use the command line entry point, you can install the package using `poetry install` and then run the command `mypackage-cli` in your terminal.

```
poetry install
mypackage-cli
```

This will execute the `main` function defined in your `cli` module. You can replace `mypackage-cli` with any name you want for your command line entry point.

**Comment by jsh9** [comment]
I creates this PR (https://github.com/masaccio/compact-json/pull/25) to address my requests No. 1 and No. 3.

And I actually found that `compact-json` is already registered within `pyproject.toml`.  The README file was just a bit outdated.  I updated the README file in my PR.

I'm not quite sure whether my No. 2 (adding a sanity checking method) above is the best idea, so I didn't implement it in my PR.

Please feel free to take over this PR and edit the code changes as needed. Thanks!

**Comment by masaccio** [comment]
Agreed that no. 2 (a deep compare of objects) is outside the scope of this package.
