### ISSUE TITLE
Cannot format non-ascii strings without unicode escape

### ISSUE THREAD

**Issue by ZeroRin** [masaccio/compact-json#4]
compact json uses `json.dumps(element)` without any configuration
https://github.com/masaccio/compact-json/blob/3b9649554237e3fb05ed6cd6fe0791007c624e7b/src/compact_json/formatter.py#L270
so that there is no way to set `ensure_ascii=False` and the output will always be with unicode escaped characters, like  `"\u5f20\u4e09"` instead of `"张三"`

I think there should be a option to control this behaviour to make the output more human friendly.

**Comment by masaccio** [comment]
Would it be safe do you think to always use `ensure_ascii=False`? I am experimenting with replacing `len(s)` for the string value with:

``` python
def string_length(self, s):
    if self.east_asian_string_widths:
        length = sum([char_display_width(c) for c in s])
        return length
    else:
        
return len(s)
```

where `string_length` is taken from this:

``` python
# From https://github.com/ncm2/ncm2
# Copyright © 2018 roxma@qq.com
def char_display_width(unicode_str):
    r = east_asian_width(unicode_str)
    if r == "F":  # Fullwidth
        return 1
    elif r == "H":  # Half-width
        return 1
    elif r == "W":  # Wide
        return 2
    elif r == "Na":  # Narrow
        return 1
    elif r == "A":  # Ambiguous, go with 2
        return 1
    elif r == "N":  # Neutral
        return 1
    else:
        return 1
```

I could be safe and test `east_asian_string_widths` to decide how to apply `ensure_ascii`. Doing this I get nicely formatted output like this:

``` text
[
    { "name": "Alice" , "age": "17"    , "occupation": "student"  },
    { "name": "Angela", "age": "42"    , "occupation": "Anwältin" },
    { "name": "张三"  , "age": "十七"  , "occupation": "学生"     },
    { "name": "依诺成", "age": "三十五", "occupation": "工程师"   }
]
```

This renders better for me in a terminal than on github.com

**Comment by masaccio** [comment]
See https://www.dropbox.com/s/qdihbgg6lhe5s8q/compact-json-issue-4.png?dl=0

**Comment by masaccio** [comment]
I've published a different change to the one in your pull request that uses a built-in for the character width. I don't look at `cells.py` much so I may have missed a load of corner-cases.

**Comment by masaccio** [comment]
Do you have some example text that I can include in a test for this? Current test is https://github.com/masaccio/compact-json/blob/main/tests/data/test-issue-4.json

**Comment by masaccio** [comment]
After looking into some corner cases where the character size is zero, I discovered https://github.com/jquast/wcwidth which seems to do what we need out-of-the-box.  The results are still not perfectly aligned though which is frustrating!

It's possible there are bugs in wcwidth. I will compare the two outputs and see if there's anything obvious but if not, I'll just merge it in.

**Comment by masaccio** [comment]
<img width="1038" alt="Screenshot 2022-12-19 at 19 49 51" src="https://user-images.githubusercontent.com/6770005/208508177-fdab50d2-4355-4d6f-b1e3-0f58f17f207f.png">

**Comment by masaccio** [comment]
I will back out the `cell_len` implementation then and just use `wcswidth`. I guess it's very sensitive to the font in use so I am going to make the bold assertion that people reading such languages will use a font that fully supports its spacing. My en_GB Terminal.app doesn't do that it seems.
