### ISSUE TITLE
Add __main__.py to support `python -m compact_json`?

### ISSUE THREAD

**Issue by ZeroRin** [masaccio/compact-json#9]
`python -m compact_json ...` seems to me as a more pythonic way of using a module as a cmdline tool. This could be done by adding a `__main__.py` with `from ._compact_json import main; main()` or directly rename `_compact_json.py` to `__main__.py`

Not sure how this would affect building the executable so I leave a issue here instead of direct PR.

**Comment by masaccio** [comment]
Published to main branch
